[package]
name        = "agnostik"
version     = "0.1.1"
description = "Executor Agnostic Runtime that can run your futures with your favourite Executor."
license     = "MIT/Apache-2.0"
authors     = ["Justus K <justus.k@protonmail.com", "Mahmut Bulut <vertexclique@gmail.com>"]
homepage    = "https://github.com/bastion-rs/agnostik"
edition     = "2018"

[features]
default = ["runtime_bastion"]
runtime_bastion = [
    "bastion-executor",
    "lightproc"
]
runtime_asyncstd = [
    "async-std",
]
runtime_tokio = [
    "tokio",
]
runtime_nostd = []

[dependencies]
bastion-executor = { version = "0.3", optional = true, features = [] }
async-std = { version = "1.3", optional = true, features = ["unstable"] }
tokio = { version = "0.2", optional = true, features = ["rt-core", "blocking", "rt-util"] }
lightproc = { version = "0.3.4", optional = true }

[dev-dependencies.tokio]
version = "0.2"
features = ["rt-core", "blocking", "time" ]
